name: check-code-quality
on:
  workflow_dispatch:
  pull_request:
    banches:
      - master
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        uses: ./.github/actions/install-deps
      - name: Check build
        run: yarn build   

  test-coverage:
    uses: ./.github/workflows/test-coverage.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  sonar-scan:
    uses: ./github/workflows/sonar-scan.yaml@master
    secrets: inherit