name: check-code-quality
on:
  workflow_dispatch:
  pull_request:
    banches:
      - master
      - 'release/**'
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    
  test-coverage:
    uses: ./.github/workflows/test-coverage.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yaml
    secrets: inherit
