name: ci-clean-arch-react-workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    banches:
      - master
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn

      - name: Check lint
        run: yarn lint

      - name: Tests
        run: yarn test:cov

      - name: Check build
        run: yarn build
