name: delete-buckets
on: 
  workflow_dispatch:
  schedule:
    # Run every sunday at 23:00 GMT-3
    - cron: '0 2 * * 0'
jobs:
  delete:
    runs-on: ubuntu-22.04
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
        # Configure AWS credentials for interacting with S3
      - name: Delete buckets
        run: for bucket in $(aws s3 ls | awk '{print $3}' | grep -E -i "^[0-9]+\.[0-9]+\.[0-9]+-(release|feature|hotfix)-[a-z]+-[0-9]+\.[0-9]+$"); do  aws s3 rb "s3://${bucket}" --force ; done
      - name: Notify on Slack
        run: echo "Deleted buckets matching regex ^[0-9]+\.[0-9]+\.[0-9]+-(release|feature|hotfix)-[a-z]+-[0-9]+\.[0-9]+$"

