# name: delete-bucket
# on: delete
# jobs:
#   delete-bucket:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Get package version == bucket name
#         run: |
#           BUCKET_NAME=$(cat package.json \
#             | grep version \
#             | head -1 \
#             | awk -F: '{ print $2 }' \
#             | sed 's/[", ]//g')
#           echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

#       - name: Check bucket existence
#         run: |
#           BUCKET_EXISTS=$(aws s3api head-bucket --bucket $BUCKET_NAME 2>&1 || true)
#           if [ ! -z "$BUCKET_EXISTS" ]; then
#             echo "Bucket $BUCKET_NAME not exists"
#             exit 1
#           fi

#       - name: Delete bucket
#         run: |
#           aws s3 rm s3://$BUCKET_NAME --recursive
#           aws s3 rb s3://$BUCKET_NAME --force

#       - name: Notify on Slack
#         run: echo "Deleted $BUCKET_NAME"
name: Delete buckets
on: workflow_dispatch
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Configure AWS credentials for interacting with S3
      - name: delete
        run: for bucket in $(aws s3 ls | awk '{print $3}' | grep "^[0-9]+\.[0-9]+\.[0-9]+-(release|feature|hotfix)-[a-z]+-[0-9]+\.[0-9]+$"); do  aws s3 rb "s3://${bucket}" --force ; done


