name: delete-bucket
on:
  delete:

jobs:
  delete-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Get bucket name
        run: |
          BUCKET_NAME=$(sed "s/\//-/g" <<< $(git branch --show-current) | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Check bucket existence
        run: |
          BUCKET_EXISTS=$(aws s3api head-bucket --bucket $BUCKET_NAME 2>&1 || true)
          if [ ! -z "$BUCKET_EXISTS" ]; then
            echo "Bucket $BUCKET_NAME not exists"
            exit 1
          fi

      - name: Delete bucket
        run: |
          aws s3 rm s3://mybucket --recursive
          aws s3 rb s3://$BUCKET_NAME --force

      - name: Notify on Slack
        run: echo "Deleted $BUCKET_NAME"