# name: delete-bucket
# on: delete
# jobs:
#   delete-bucket:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Get package version == bucket name
#         run: |
#           BUCKET_NAME=$(cat package.json \
#             | grep version \
#             | head -1 \
#             | awk -F: '{ print $2 }' \
#             | sed 's/[", ]//g')
#           echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

#       - name: Check bucket existence
#         run: |
#           BUCKET_EXISTS=$(aws s3api head-bucket --bucket $BUCKET_NAME 2>&1 || true)
#           if [ ! -z "$BUCKET_EXISTS" ]; then
#             echo "Bucket $BUCKET_NAME not exists"
#             exit 1
#           fi

#       - name: Delete bucket
#         run: |
#           aws s3 rm s3://$BUCKET_NAME --recursive
#           aws s3 rb s3://$BUCKET_NAME --force

#       - name: Notify on Slack
#         run: echo "Deleted $BUCKET_NAME"
name: Branch Deleted
on: delete
jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          BUCKET_NAME=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[", ]//g')
          echo $BUCKET_NAME