name: deploy-prod
on:
  workflow_dispatch:
    inputs:
      version-name:
        description: 'Version name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      VERSION_NAME: ${{ inputs.version-name }}
      BUCKET_NAME: ${{ vars.S3_MASTER_BUCKET_PREFIX }}-${{ inputs.version-name }}
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
        # Configure AWS credentials for interacting with S3
      - name: Check S3 bucket existence
        run: |
          BUCKET_EXISTS=$(aws s3api head-bucket --bucket $BUCKET_NAME 2>&1 || true)
          if [ ! -z "$BUCKET_EXISTS" ]; then
            echo "Bucket $BUCKET_NAME not exists"
            exit 1
          fi
      - name: Copy bucket content to master bucket
        run: |
          aws s3 sync s3://$BUCKET_NAME s3://${{ vars.S3_MASTER_BUCKET_NAME }}
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      - name: Notify on Slack
        run: echo "Deployed $VERSION_NAME to production"